name: marker-api
on: [push]
env:
  PYTHON_VER: "3.10"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v1
      - name: Install Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Run the black lint check
        run: |
          pip install black
          black . --check